apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ .siteid }}-tenant-namespace
  namespace: flux-system
  labels:
    demo: "true"
spec:
  chart:
    spec:
      chart: charts/mendel-tenant-namespace
      sourceRef:
        kind: GitRepository
        name: flux-sync
        namespace: flux-system
  interval: 1m0s
  install:
    timeout: "60s"
    remediation:
      retries: 3
  values:
    global:
      siteId: {{ .siteid }}
      environment: stage
      namespaceAdditionalLabels:
        privateRepoAccess: "true"

    externalSecrets:
      secretStoreRef: mendel-cluster-store
      secretStoreKind: ClusterSecretStore
      remoteSecretName: TST2_TENANT_SECRET
      inClusterSecretName: {{ .siteid }}-tenant-secret

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ .siteid }}-tenant
  namespace: {{ .siteid }}-pipeline
  labels:
    demo: "true"
spec:
  chart:
    spec:
      chart: mendel-tenant
      sourceRef:
        kind: HelmRepository
        name: mendel-health
        namespace: flux-system
      version: 0.0.15
  interval: 1m0s
  install:
    timeout: "10m"
    remediation:
      retries: 3
  dependsOn:
    - name: {{ .siteid }}-tenant-namespace
      namespace: flux-system
  values:
    global:
      siteId: {{ .siteid }}
      environment: stage
      targetNamespace: {{ .siteid }}-pipeline

      provisioning:
        tenantSecret: {{ .siteid }}-tenant-secret
        tenantFileName: payload.json
        tenantServiceAddress: http://tenant-service.infra/tenants

    services:
      - bt-job-server
      - fs-sync
      - mendel-flow
      - patient-doc
      - pipeline-state
      - rt-job-server
      - ooo-datastore
      - spark-manager
#      - carbon

    bt-job-server:
      helmVersion: 0.0.5
      values:
        tag: 0.9.2
        env:
          gcsPath: "gs://mendel-{{ .siteid }}-pipeline"

    fs-sync:
      helmVersion: 0.0.4
      values:
        tag: 0.0.4

    mendel-flow:
      helmVersion: 0.0.7
      values:
        tag: 0.5.11
        env:
          # -- the gcs location of the flow-definitions
          flowDefinition: "gs://mendel-{{ .siteid }}-pipeline/config/flow-definition"
          dryRun: false
          redis:
            prefix: {{ .siteid }}-flow
          emr:
            stagingBasePath: "gs://mendel-{{ .siteid }}-pipeline/sandbox/default/pipeline-steps"
            url: "db-postgresql.pg"

    patient-doc:
      helmVersion: 0.0.8
      values:
        tag: 0.5.11-DEVELOP
        env:
          es:
            savedQueryIndex: {{ .siteid }}_saved_query
            documentFullTextIndex: {{ .siteid }}_phi_fulltext
            documentSearchIndex: {{ .siteid }}_document_search_staging
          redis:
            prefix: {{ .siteid }}-doc
          deid:
            url: jdbc:postgresql://db-postgresql.pg.svc.cluster.local:5432/{{ .siteid }}
          phi:
            url: jdbc:postgresql://db-postgresql.pg.svc.cluster.local:5432/{{ .siteid }}

    pipeline-state:
      helmVersion: 0.0.10
      values:
        tag: 0.6.8
        env:
          siteId: {{ .siteid }}
          sandboxData: "gs://mendel-{{ .siteid }}-pipeline/sandbox/default/data"
          redis:
            prefix: {{ .siteid }}-pipeline-state
          state:
            url: jdbc:postgresql://db-postgresql.pg.svc.cluster.local:5432/{{ .siteid }}

    rt-job-server:
      helmVersion: 0.0.6
      values:
        tag: 0.0.23
        env:
          state:
            url: jdbc:postgresql://db-postgresql.pg.svc.cluster.local:5432/{{ .siteid }}

    ooo-datastore:
      helmVersion: 0.0.10
      values:
        tag: 0.5.11-DEVELOP
        provisioning:
          auth0:
            audienceUserAccess: "https://mendel-staging.us.auth0.com/api/v2/"
        env:
          rulesFilesBasepath: gs://mendel-{{ .siteid }}-data/export_rules
          redis:
            prefix: {{ .siteid }}-ooo
          pg:
            url: jdbc:postgresql://db-postgresql.pg.svc.cluster.local:5432/{{ .siteid }}
          emr:
            url: jdbc:postgresql://db-postgresql.pg.svc.cluster.local:5432/{{ .siteid }}

    spark-manager:
      helmVersion: 0.0.4
      values:
        tag: 0.0.2
        siteId: "{{ .siteid }}"

    carbon:
      targetNamespace: {{ .siteid }}-product
      helmVersion: 0.1.0
      values:
        tag: 1.0.1-DEVELOP
        namespace: {{ .siteid }}-product
