
name: This is callable workflow
env:
  HELM_CHART: hello-chart
  MESSAGE: ${{ github.event.client_payload.message. }}
on:
  repository_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello ${{ env.MESSAGE }}"
