name: Build and publish helm chart test
env:
  HELM_CHART: hello-chart
on:
  push:
    paths:
      - "hello-chart/**"
      - ".github/workflows/ci.yaml"
    branches:
      - main
  pull_request:
    paths:
      - "hello-chart/**"
      - ".github/workflows/ci.yaml"

concurrency:
  group: ${{ github.ref }}-helm

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1

      - name: Setup python
        uses: actions/setup-python@v2

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0

      - name: Run chart-testing (lint)
        run: ct lint --charts=$HELM_CHART --validate-maintainers=false
  release:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.MENDEL }}
      - name: Build and upload helm package
        run: |
          CHART_FILE=$(helm package -d /tmp $HELM_CHART | awk '{print $NF}')
          helm push $CHART_FILE oci://us-central1-docker.pkg.dev/mendel-health/softwares/

